---
# Role tasks
- block:
    - name: Ensure umask is predefined in file
      shell: "cat {{ default_umask_file_path }} | grep -v '^#'"
      register: default_umask_read_file_result
      changed_when: no

    - name: Replace umask entries if needed
      replace:
        path: "{{ default_umask_file_path }}"
        regexp: '^(\s*umask)(.*)$'
        replace: '\1 {{ default_umask_value }}'
      when: default_umask_read_file_result.stdout is search("umask")

    - name: Insert umask value if needed
      lineinfile:
        path: "{{ default_umask_file_path }}"
        insertafter: EOF
        line: "umask {{ default_umask_value }}"
      when: default_umask_read_file_result.stdout is not search("umask")
  tags:
    role::default_umask
