---
# Role tasks
- block:

    - include_tasks: adjust_umask.yml
      loop: "{{ default_umask_files }}"
      loop_control:
        loop_var: default_umask_file_path

  tags:
    - role::default_umask
